global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rails_app"
    static_configs:
      - targets: ["web:9394"]

  - job_name: "prometheus_exporter"
    static_configs:
      - targets: ["prometheus_client:9394"]
